export default games = [
    {
        id: 1,
        title: `Assassin's Creed: Valhalla`,
        teaser: `In Assassin's Creed® Valhalla, you are Eivor, a fierce Viking warrior raised of battle and glory.`,
        description: `Explore a dynamic and beautiful open world set against the brutal backdrop of England's Dark Ages. Raid your enemies, grow your settlement, and build your political power in your quest to earn your place among the gods in Valhalla.`,
        rating: 4.5,
        category: ['Action', 'RPG'],
        age: '15+',
        cover: require('./assets/games/assassins_creed/assassins_creed_1.jpg'),
        screenshots: [
            require('./assets/games/assassins_creed/assassins_creed_2.jpg'),
            require('./assets/games/assassins_creed/assassins_creed_3.jpg'),
            require('./assets/games/assassins_creed/assassins_creed_4.jpg'),
            require('./assets/games/assassins_creed/assassins_creed_5.jpg'),
            require('./assets/games/assassins_creed/assassins_creed_6.jpg'),
            require('./assets/games/assassins_creed/assassins_creed_7.jpg'),
            require('./assets/games/assassins_creed/assassins_creed_8.jpg'),
        ],
        backgroundColor: '#6A493D',
    },
    {
        id: 2,
        title: 'FIFA 21',
        teaser: 'Win as one in FIFA 21 with new ways to team up and express yourself on the street and in the stadium.',
        description: 'Powered by Frostbite™, FIFA 21 raises the game with fresh features that let you enjoy even bigger victories together in VOLTA FOOTBALL and FIFA Ultimate Team™',
        rating: 4.8,
        category: ['Sports'],
        age: '8+',
        cover: require('./assets/games/fifa_21/fifa_1.jpg'),
        screenshots: [
            require('./assets/games/fifa_21/fifa_2.jpg'),
            require('./assets/games/fifa_21/fifa_3.jpg'),
            require('./assets/games/fifa_21/fifa_4.jpg'),
            require('./assets/games/fifa_21/fifa_5.jpg'),
            require('./assets/games/fifa_21/fifa_6.jpg'),
            require('./assets/games/fifa_21/fifa_7.jpg'),
            require('./assets/games/fifa_21/fifa_8.jpg'),
            require('./assets/games/fifa_21/fifa_9.jpg'),
        ],
        backgroundColor: '#1F3F85',
    },
    {
        id: 3,
        title: 'COD: Black Ops Cold War',
        teaser: `Black Ops Cold War will drop fans into the depths of the Cold War's volatile geopolitical battle of the early 1980s.`,
        description: 'As elite operatives, you will follow the trail of a shadowy figure named Perseus who is on a mission to destabilize the global balance of power and change the course of history.',
        rating: 4.1,
        category: ['Action', 'Multiplayer', 'Strategy'],
        age: '15+',
        cover: require('./assets/games/cod/cod_1.jpg'),
        screenshots: [
            require('./assets/games/cod/cod_2.jpg'),
            require('./assets/games/cod/cod_3.jpg'),
            require('./assets/games/cod/cod_4.jpg'),
            require('./assets/games/cod/cod_5.jpg'),
            require('./assets/games/cod/cod_6.jpg'),
            require('./assets/games/cod/cod_7.jpg'),
            require('./assets/games/cod/cod_8.jpg'),
        ],
        backgroundColor: '#34201D',
    },
    {
        id: 4,
        title: `Spider-Man: Miles Morales`,
        teaser: 'Teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker.',
        description: 'New features, new innovations and a fresh approach make DIRT 5 a hub of off-road racing, style and culture, where you can constantly create highlight-reel moments.',
        rating: 4.0,
        category: ['Adventure'],
        age: '12+',
        cover: require('./assets/games/spider_man/spider_man_1.jpg'),
        screenshots: [
            require('./assets/games/spider_man/spider_man_2.jpg'),
            require('./assets/games/spider_man/spider_man_3.jpg'),
            require('./assets/games/spider_man/spider_man_4.jpg'),
            require('./assets/games/spider_man/spider_man_5.jpg'),
        ],
        backgroundColor: '#A71E15',
    },
    {
        id: 5,
        title: 'DIRT 5',
        teaser: 'DIRT 5 writes a new chapter in the legacy of DIRT - bolder and braver than ever before.',
        description: 'New features, new innovations and a fresh approach make DIRT 5 a hub of off-road racing, style and culture, where you can constantly create highlight-reel moments.',
        rating: 3.5,
        category: ['Racing', 'Multiplayer'],
        age: '3+',
        cover: require('./assets/games/dirt_5/dirt_1.jpg'),
        screenshots: [
            require('./assets/games/dirt_5/dirt_2.jpg'),
            require('./assets/games/dirt_5/dirt_3.jpg'),
            require('./assets/games/dirt_5/dirt_4.jpg'),
            require('./assets/games/dirt_5/dirt_5.jpg'),
            require('./assets/games/dirt_5/dirt_6.jpg'),
            require('./assets/games/dirt_5/dirt_7.jpg'),
        ],
        backgroundColor: '#FD1A7B',
    },
    {
        id: 6,
        title: 'NBA 2K21',
        teaser: 'NBA 2K21 is the latest title in the world-renowned, best-selling NBA 2K series.',
        description: 'New features, new innovations and a fresh approach make DIRT 5 a hub of off-road racing, style and culture, where you can constantly create highlight-reel moments.',
        rating: 4.7,
        category: ['Sports'],
        age: '8+',
        cover: require('./assets/games/nba/nba_1.jpg'),
        screenshots: [
            require('./assets/games/nba/nba_2.jpg'),
            require('./assets/games/nba/nba_3.jpg'),
            require('./assets/games/nba/nba_4.jpg'),
            require('./assets/games/nba/nba_5.jpg'),
            require('./assets/games/nba/nba_6.jpg'),
            require('./assets/games/nba/nba_7.jpg'),
            require('./assets/games/nba/nba_8.jpg'),
        ],
        backgroundColor: '#F71F26',
    },
]